# Tasks

GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRzcmNtMFhnMlk0N0QxWGxwWDBrUCJ9.eyJpc3MiOiJodHRwczovL2Rldi1maWxvLnVrLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2Nzc3ZWFiZDIxNDQ3MDA3ZDk3YTllYjAiLCJhdWQiOlsiaHR0cHM6Ly9kZXYtZmlsby51ay5hdXRoMC5jb20vYXBpL3YyLyIsImh0dHBzOi8vZGV2LWZpbG8udWsuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTczNTkxMzkwNiwiZXhwIjoxNzM2MDAwMzA2LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiRlk3cW1xcDVMTkZDT0k4cEVyeDRTamU0RG1ZYWNYdWoifQ.Wlf-zfNsdlupH-Zk6Jv4OhqGTBWoJug6562PWzrue3w1A8JSSYPDy-VbKJvj4cwoSJ0T_3H6YTEbP8J9jyGxa29QkaEdUEMStD1qJQgox4QhWDzbN1cSM53ZVr8xGjbcL94QSgmGxZ6l6RBSOucI-wJoZBDC3mBvFK8ZmLERD2WGQ_S8bag_-O0tj_BzCUUTGw5s-G_rzif_I4MnFS06dWaltmIviIcrahdMMlqlrrcThS4f8j9Mpi9nrZ_J3HIorSU7JgfdEznYGUxrKRqO_TBWfqRAfumXQFEb3SPkw5rk8cvv-J2_T7re68GLFq5eiVYZgz3tAZM04GaX-YslPg